name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: "Molapour80"
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark
