name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:     # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Snake Game
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: "Molapour80"  # Your GitHub username
          outputs: |
            assets/github-contribution-snake.svg
            assets/github-contribution-snake-dark.svg?palette=github-dark
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snake-game
          path: assets/
